### ISSUE TITLE
[BE][개발] Jwt 보안 2차 개발

### ISSUE THREAD

**Issue by JihooKang-KOR** [codestates-seb/seb42_main_011#14]
# ✅ 목표 : Jwt 보안 2차 개발
### 🐶 담당자 :  백엔드

-----

## ⏺ 할일
- [x] getSecurityContext()를 이용하여 global하게 사용할 수 있는 authentication을 return하는 method 구현
- [x] **Jwt** 로그아웃 구현 (Redis를 사용할 가능성 높음 / Spring Security에 있는 logout은 session용)
- [x] Refresh token 구현 (Redis 사용)
- [x] AuthenticationFilter에서 refresh token을 쿠키의 형태로 리팩토링

**Comment by sdoaolo** [comment]
#155
