### ISSUE TITLE
[BE]  endpoint   /api/v1으로 시작하도록 변경

### ISSUE THREAD

**Issue by sdoaolo** [codestates-seb/seb42_main_011#31]
# ✅ 목표 :  endpoint   /api/v1으로 시작하도록 변경
### 🐶 담당자 : BE

배포관련 이슈 발생 여부를 우려해 api 요청 엔드포인트를 변경하기로 결정되었습니다. 

-----

## ⏺ 할일
- [ ] 각자 담당한 부분 변경 해두기

**Comment by JihooKang-KOR** [comment]
Member에는 적용 완료입니다.

**Comment by sdoaolo** [comment]
Comment, Amenity에도 적용 완료되어있습니다. 
BulletinPost 완료 이후에 Close 부탁드릴게요!

**Comment by sdoaolo** [comment]
bulletinpost 엔드포인트 변경 확인하여 close 합니다
